*******************************************************************************
****** AND2X2 schematic AND2X1  <vs>  AND2X2 layout AND2X1
*******************************************************************************

Filter/Reduce statistics only. Network matching was OK.
                                                                                                                                                                   
Pre-expand Statistics                      
======================                          Original       
Cell/Device                               schematic  layout
(g45p1svt) MOS                                    3       6*
(g45n1svt) MOS                                    3       6*
                                             ------  ------
Total                                             6      12

Reduce Statistics
=================                               Original             Reduced
Cell/Device                               schematic  layout   schematic  layout
(g45n1svt) MOS                                    3       6*          1       1
(g45p1svt) MOS                                    3       6*          1       1
(g45n1svt:SerMos2#1) MosBlk                       -       -           1       1
(g45p1svt:ParMos2#1) MosBlk                       -       -           1       1
                                             ------  ------      ------  ------
Total                                             6      12           4       4

Schematic and Layout Match
