*******************************************************************************
****** AO21X1 schematic AO21X1  <vs>  AO21X1 layout AO21X1
*******************************************************************************

Filter/Reduce statistics only. Network matching was OK.
                                                                                                                                                                   
Pre-expand Statistics                      
======================                          Original       
Cell/Device                               schematic  layout
(g45n1svt) MOS                                    4       4
(g45p1svt) MOS                                    4       4
                                             ------  ------
Total                                             8       8

Reduce Statistics
=================                               Original             Reduced
Cell/Device                               schematic  layout   schematic  layout
(g45n1svt) MOS                                    4       4           2       2
(g45p1svt) MOS                                    4       4           1       1
(g45n1svt:SerMos2#1) MosBlk                       -       -           1       1
(g45p1svt:ParMos2#1) MosBlk                       -       -           1       1
(g45p1svt:SerMos3#1) MosBlk                       -       -           1       1
                                             ------  ------      ------  ------
Total                                             8       8           6       6

Schematic and Layout Match
