*******************************************************************************
****** AO21X2 schematic AO21X2  <vs>  AO21X2 layout AO21X2
*******************************************************************************

Filter/Reduce statistics only. Network matching was OK.
                                                                                                                                                                   
Pre-expand Statistics                      
======================                          Original       
Cell/Device                               schematic  layout
(g45p1svt) MOS                                    4       8*
(g45n1svt) MOS                                    4       8*
                                             ------  ------
Total                                             8      16

Reduce Statistics
=================                               Original             Reduced
Cell/Device                               schematic  layout   schematic  layout
(g45n1svt) MOS                                    4       8*          2       2
(g45p1svt) MOS                                    4       8*          1       1
(g45n1svt:SerMos2#1) MosBlk                       -       -           1       1
(g45p1svt:ParMos2#1) MosBlk                       -       -           1       1
(g45p1svt:SerMos3#1) MosBlk                       -       -           1       1
                                             ------  ------      ------  ------
Total                                             8      16           6       6

Schematic and Layout Match
