*******************************************************************************
****** AO21X4 schematic AO21X4  <vs>  AO21X4 layout AO21X4
*******************************************************************************

Filter/Reduce statistics only. Network matching was OK.
                                                                                                                                                                   
Pre-expand Statistics                      
======================                          Original       
Cell/Device                               schematic  layout
(g45p1svt) MOS                                    4      16*
(g45n1svt) MOS                                    4      16*
                                             ------  ------
Total                                             8      32

Reduce Statistics
=================                               Original             Reduced
Cell/Device                               schematic  layout   schematic  layout
(g45n1svt) MOS                                    4      16*          2       2
(g45p1svt) MOS                                    4      16*          1       1
(g45n1svt:SerMos2#1) MosBlk                       -       -           1       1
(g45p1svt:ParMos2#1) MosBlk                       -       -           1       1
(g45p1svt:SerMos3#1) MosBlk                       -       -           1       1
                                             ------  ------      ------  ------
Total                                             8      32           6       6

Schematic and Layout Match
