*******************************************************************************
****** BUFX2 schematic BUFX2  <vs>  BUFX2 layout BUFX2
*******************************************************************************

Filter/Reduce statistics only. Network matching was OK.
                                                                                                                                                                   
Pre-expand Statistics                      
======================                          Original       
Cell/Device                               schematic  layout
(g45p1svt) MOS                                    2       4*
(g45n1svt) MOS                                    2       4*
                                             ------  ------
Total                                             4       8

Reduce Statistics
=================                               Original             Reduced
Cell/Device                               schematic  layout   schematic  layout
(g45n1svt) MOS                                    2       4*          2       2
(g45p1svt) MOS                                    2       4*          2       2
                                             ------  ------      ------  ------
Total                                             4       8           4       4

Schematic and Layout Match
